package com.ford.demo.model;


import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity

public class Event {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String name;
    private String organizer;
    private String email;
    private String phone;

    @JsonFormat(pattern = "yyyy-MM-dd")
    @Column(name = "e_date")
    private LocalDate e_date;

    private String location;
    private String duration;
    @Column(name = "no_of_part")
    private Integer no_of_part;
    @Column(name = "max_participants")
    private Integer maxParticipants; // Ensure this is present
    private String e_mode;
    private String description;

    // Getters and Setters (auto-generated by Lombok @Data)
}

